services:
  conidea-api:
    image: conidea-api:latest
    build:
      context: .
      dockerfile: apps/conidea-api/Dockerfile
    container_name: conidea-api
    ports:
      - '3000:3000'
    environment:
      HOST: 0.0.0.0
      PORT: 3000
      MONGO_URI: mongodb://mongo:27017/conidea
      RABBITMQ_URI: amqp://rabbitmq:5672
    restart: unless-stopped
  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - '5672:5672' # AMQP protocol port
      - '15672:15672' # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: unless-stopped

volumes:
  mongo-data:
