name: CI

on:
  push:
    branches:
      - distributed
  pull_request:
    branches:
      - distributed

permissions:
  contents: write
  actions: write
  pull-requests: write

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js LTS
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3

      - name: Install Dependencies
        run: npm ci
        env:
          CI: true

      # Ensure conidea-api is built before deployment
      - name: Build conidea-api
        if: github.ref == 'refs/heads/distributed'
        run: npx nx build conidea-api
      - name: Deploy to Azure Web App
        if: github.ref == 'refs/heads/distributed'
        uses: azure/webapps-deploy@v2
        with:
          app-name: bthesis-conidea-api
          slot-name: production
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: dist/apps/conidea-api
