name: CI

on:
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js LTS
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3

      - run: npm install @nx/nx-linux-x64-gnu
      - name: Install Dependencies
        run: npm ci
        env:
          CI: true

      # This line is needed for nx affected to work when CI is running on a PR
      - run: git branch --track main origin/main

      - run: npx nx format:check
      - run: npx nx affected -t lint,test,build --parallel=3
